name: gitvision
description: "Eurovision-themed GitHub commit mood analyzer with Spotify integration for 120-minute developer workshop"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  http: ^1.4.0
  sentiment_dart: ^0.0.5
  url_launcher: ^6.2.7
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/eurovision_github_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon/eurovision_github_icon_foreground.png"
  ios_content_mode: scaleAspectFit
  macos:
    generate: true
    image_path: "assets/icon/eurovision_github_icon.png"
